excel_file/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'excel_file.views.index', name='index'),
    url(r'^load/$', 'excel_file.views.load_data', name='load_data'),
    url(r'^get/$', 'excel_file.views.get_data', name='get_data')
]

test_icl/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('excel_file.urls', namespace='excel_file')),
]

excel_file/models.py
from django.db import models

# Create your models here.
class Coordinate(models.Model):
    x = models.FloatField()
    y = models.FloatField()

excel_file/forms.py
from django import forms


class ExcelFileForm(forms.Form):
    file = forms.FileField(label='', 
                           widget=forms.FileInput(attrs={'class':'my_class'}))

excel_file/views.py
import os
import xlrd

from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from excel_file.forms import ExcelFileForm
from excel_file.models import Coordinate


# Create your views here.
def index(request):
    file_form = ExcelFileForm()
    return render(request, 'excel_file/index.html', context={'file_form': file_form})

@csrf_exempt
def load_data(request):
    request.upload_handlers.pop(0)
    return _load_data(request)

@csrf_protect
def _load_data(request):
    if request.method == "POST":
        file_form = ExcelFileForm(request.POST, request.FILES)
        if file_form.is_valid():
            try:
                f = request.FILES['file']
                book = xlrd.open_workbook(f.temporary_file_path())
                sheet = book.sheet_by_index(0)
                coordinates = []
                #Cycle for checking of right data
                for row in range(10):
                    coordinates.append(Coordinate(x=sheet.cell_value(row, 0), y=sheet.cell_value(row, 1)))
                #Save into a database
                Coordinate.objects.all().delete()
                for coordinate in coordinates:
                    coordinate.save()
            except:
                return JsonResponse({'errors': ['Incorrect xls/xlsx']})
            return JsonResponse({'errors': [] })
        else:
            return JsonResponse({'errors': ['Form is invalid']})
    return JsonResponse({'errors': ['Method is not POST']})


def get_data(request):
    coordinates = Coordinate.objects.all()
    data = {'coordinates':[]}
    for coordinate in coordinates:
        data['coordinates'].append((coordinate.x, coordinate.y))
    return JsonResponse(data)

excel_file/templates/excel_file/index.html
<html ng-app="testApp">
    <head>
        {% load staticfiles %}
        <title>Main Page</title>
        <link rel="stylesheet" type="text/css" href="{% static 'excel_file/css/graphic.style.css' %}"/>

        <script type="text/javascript" src="{% static 'js/angular.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.flot.min.js' %}"></script>
        <script type="text/javascript">
            
            var myApp = angular.module("testApp", []);

            myApp.controller('FileUploadController', ['$scope', function($scope){
                $scope.load = function(){
                    var formData = new FormData(document.forms.fileupload);
                    var xhr = new XMLHttpRequest();
                    xhr.open("POST", "{% url 'excel_file:load_data' %}");
                    xhr.send(formData);
                    xhr.onreadystatechange = function(){
                        if(xhr.readyState != 4) return;
                        if(xhr.status == 200){
                            var answer = JSON.parse(xhr.responseText);
                            if (answer.errors.length != 0){
                                alert(answer.errors);
                            }
                        }else{
                            alert(xhr.status + ': ' + xhr.statusText);
                        }
                    };
                    
                };
            }]);

            myApp.controller('GetCoordinatesController', ['$scope', '$http', function($scope, $http){
                $scope.getInfo = function(){
                    $http({
                        method : 'GET',
                        url : "{% url 'excel_file:get_data' %}"})
                    .then(function success(response){
                        var answer = response.data;
                        if(answer.coordinates.length == 0){
                            alert('Данных нет');
                        }else{
                            var coordinates = answer.coordinates;
                            var options = {
                                points: {show: true, fill: true, lineWidth: 4, fillColor: "#000000"},
                                grid: {
                                    borderWidth: {
                                        top: 0,
                                        left: 2,
                                        bottom: 2,
                                        right: 0
                                    },
                                    hovarable: true
                                }
                            };
                            $.plot($('#graphic'), [coordinates], options);
                        }
                    }, function error(response){
                        alert('Error!');
                    });
                };
            }]);
        </script>
    </head>

    <body>
        <form name="fileupload" ng-controller="FileUploadController" enctype="multipart/form-data">
            {% csrf_token %}
            {{ file_form.as_p }}
            <input name="sendfile" type="button" ng-click="load()" value="OK"/>
        </form>
        <div ng-controller="GetCoordinatesController">
            <input ng-click="getInfo()" type="button" value="Нарисовать график"/>
            
        </div>
        <div id="graphic">

        </div>
    </body>
</html>